### ISSUE TITLE
Release new version to npm?

### ISSUE THREAD

**Issue by Simon-Briggs** [tonystar/bootstrap-float-label#13]
Hi, thanks for this library.

Are you planning on releasing a newer version to NPM? Version 4.0.1 doesn't work on firefox, so to get around that, I've been pulling your latest version from github. I've had no problems with that so far, but being able to pull from npm will be a little neater.

```
    "bootstrap-float-label": "https://github.com/tonystar/bootstrap-float-label.git",
```

**Comment by tonystar** [comment]
Let's fo!

**Comment by tonystar** [comment]
@Simon-Briggs done! Thanks for submitting the issue!

*Is issue fixed for you? => Support the project by [★ starring base project on GitHub](https://github.com/tonystar/float-label-css) and [sharing on Twitter](https://twitter.com/tonystarring/status/787217405827317762)!*
