### ISSUE TITLE
Placeholders don't display properly in Firefox

### ISSUE THREAD

**Issue by rdebeasi** [tonystar/bootstrap-float-label#14]
In Firefox 53, the labels and placeholders are displayed over each other. This problem affects both v3 and v4 of bootstrap-float-label.

Edit: Actually this only affects v3. The CodePen for v4 is affected, but the actual v4 code in GitHub is not.

![screenshot from 2017-06-22 13-34-33](https://user-images.githubusercontent.com/1299370/27447655-d0fb0562-574f-11e7-9a03-be9021c6eca7.png)

Otherwise, this library rocks - thanks for creating it! :)

**Comment by tonystar** [comment]
Thanks for reporting! and feedback! Should be fixed now! also updated npm fo v3.

**Comment by tonystar** [comment]
Commited in 1f245bb7ed212d2ae95f813f7c0680f3e8a3167f
