### ISSUE TITLE
Match placeholder text size?

### ISSUE THREAD

**Issue by KeithGillette** [tonystar/bootstrap-float-label#15]
Love the float label!

For my purposes, I'd like to have the label text the same size as the placeholder text instead of 150%. How would one accomplish that and keep the floated label positioned and sized appropriately?

**Comment by tonystar** [comment]
@KeithGillette simply play around the values:
```
.has-float-label .form-control:placeholder-shown:not(:focus) + * {
  font-size: 150%;
  top: .3em;
}
```

Also I'm going to provide more pre-configured variants here: https://github.com/tonystar/bootstrap-float-label/issues/4.

**Comment by KeithGillette** [comment]
Duh. I had adjusted that selector, but naively simply deleted the `font-size` property instead of changing its  value, thinking the former would allow the underlying font-size to be asserted. Look forward to seeing the forthcoming variants. Thanks!

**Comment by tonystar** [comment]
Ah, ok! Stay tuned!
